version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins5
    ports:
      - "8085:8080"
      - "50005:50000"
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  sampleeapp:
    build: ./sampleapp
    container_name: sampleeapp
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "3005:3005"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "85:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sampleeapp
    restart: unless-stopped

networks:
  default:
    name: infra-net